on:
  pull_request:
    types:
      - opened
      - reopened
      - labeled
      - unlabeled
      - synchronize
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: write
  pull-requests: write

name: Integration

jobs:
  lint:
    if: ${{ !contains(fromJSON('["labeled", "unlabeled"]'), github.event.action) }}
    name: Integrate
    uses: gitops-ci-cd/.github/.github/workflows/lint.yaml@main

  test:
    if: ${{ !contains(fromJSON('["labeled", "unlabeled"]'), github.event.action) }}
    name: Integrate
    uses: gitops-ci-cd/.github/.github/workflows/test.yaml@main

  bump:
    name: Integrate
    uses: gitops-ci-cd/.github/.github/workflows/bump.yaml@main

  auto-merge:
    name: Check auto-merge
    uses: gitops-ci-cd/.github/.github/workflows/auto_merge.yaml@main
