on:
  push:
    paths-ignore:
      - .devcontainer/**
      - .github/**
      - .vscode/**
      - .gitignore
      - Brewfile
      - README.md
    branches:
      - main

permissions:
  contents: write

name: Release

jobs:
  release:
    name: Release
    uses: gitops-ci-cd/.github/.github/workflows/release.yaml@main
